<?php
/*
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ReleansAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Response2001 implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $senderName public property
     */
    public $senderName;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $phoneNumber public property
     */
    public $phoneNumber;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $status public property
     */
    public $status;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $id          Initialization value for $this->id
     * @param string  $senderName  Initialization value for $this->senderName
     * @param string  $phoneNumber Initialization value for $this->phoneNumber
     * @param integer $status      Initialization value for $this->status
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->id          = func_get_arg(0);
            $this->senderName  = func_get_arg(1);
            $this->phoneNumber = func_get_arg(2);
            $this->status      = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']          = $this->id;
        $json['senderName']  = $this->senderName;
        $json['phoneNumber'] = $this->phoneNumber;
        $json['status']      = $this->status;

        return $json;
    }
}
