<?php
/*
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ReleansAPILib;

use ReleansAPILib\Controllers;

/**
 * ReleansAPILib client class
 */
class ReleansAPIClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $oAuthAccessToken = null
    ) {
        Configuration::$oAuthAccessToken = $oAuthAccessToken ? $oAuthAccessToken : Configuration::$oAuthAccessToken;
    }
    /**
     * Singleton access to Message controller
     * @return Controllers\MessageController The *Singleton* instance
     */
    public function getMessage()
    {
        return Controllers\MessageController::getInstance();
    }
    /**
     * Singleton access to Sender controller
     * @return Controllers\SenderController The *Singleton* instance
     */
    public function getSender()
    {
        return Controllers\SenderController::getInstance();
    }
    /**
     * Singleton access to Balance controller
     * @return Controllers\BalanceController The *Singleton* instance
     */
    public function getBalance()
    {
        return Controllers\BalanceController::getInstance();
    }
}
